### ISSUE TITLE
some devices not found

### ISSUE THREAD

**Issue by 1337heker** [Samsung-Loki/Syndical#1]
example: Syndical.Application -m Fetch -M SM-S757BL -r TFN

but if you have specific version string you can download firmware of it ( not with default built app, cause it will say device does not exist )

but with samloader
./samloader -m SM-S757BL -r TFN download -v S757BLUDS8BTJ1/S757BLTFN8BTJ1/S757BLUDS8BTJ1/S757BLUDS8BTJ1 -O .

so that means samsung possibly has another XML server

**Comment by TheAirBlow** [comment]
Can you properly expain the issue?

**Comment by 1337heker** [comment]
> Can you properly expain the issue?

there is a phone SM-S757BL with a region of TFN

the program does not find latest firmware for it.

it's missing in the fota xml apperantly.
btw, it's not the only model that has problem like this

edit: if you download a firmware for it, it works
`csc: TFN fw_version: S757BLUDS8BTJ1/S757BLTFN8BTJ1/S757BLUDS8BTJ1/S757BLUDS8BTJ1 os_version: Pie(Android 9) build_date: 20201030180035`

**Comment by TheAirBlow** [comment]
This is not Syndical's issue. It's Samsung's shit. I'll keep it opened to
look at it later.

пн, 13 дек. 2021 г., 20:36 yEsPaP ***@***.***>:
