### ISSUE TITLE
Request: Support for .NET v7.0 framework and openssl v3

### ISSUE THREAD

**Issue by nt74** [Samsung-Loki/Syndical#10]
Hello,
I have created an [AUR package](https://aur.archlinux.org/packages/syndical) for this repo and was wondering if future plans to implement this project with?

- .NET v7.0 framework
- openssl v3+

**Comment by TheAirBlow** [comment]
Updated to net7.0 but can't be bothered to port the obsolete APIs for now, focused on other projects.
No clue what you mean with openssl v3+
