### ISSUE TITLE
FUS and decryption keys need updating

### ISSUE THREAD

**Issue by TheRealMrWicked** [Samsung-Loki/Syndical#12]
Samsung made some recent changes preventing downloads since the latest smart switch update, both [Frija](https://github.com/SlackingVeteran/frija/releases/tag/v2.0.23357.1) and [Bifrost](https://github.com/zacharee/SamloaderKotlin/releases/tag/1.16.3) have been updated and work properly now.

See [this commit](https://github.com/zacharee/SamloaderKotlin/commit/e0766d729e9b7640793b26ade4f3a0e8af1752d8) from Bifrost for exactly what I am talking about.

I am making the issue just to notify you of the issue.

(Also not related to the current issue, but I think you should update the binaries provided in the releases section for people who may not know how to compile the C# code.)

Thank you - MrWicked

**Comment by TheAirBlow** [comment]
Will push out a 1.1.0 soon enough, updated the keys too.
