### ISSUE TITLE
FUS Now Requires a Valid IMEI or Serial Number

### ISSUE THREAD

**Issue by TheRealMrWicked** [Samsung-Loki/Syndical#13]
Once again Samsung has made changes now requiring a valid IMEI or Serial number to download Firmware from their servers.

Bifrost has been updated and works properly, see [this commit](https://github.com/zacharee/SamloaderKotlin/commit/b1d003065835d15e9445b3bd53cf50183274e275) for the implementation.

Thank you - MrWicked

**Comment by RealMrWicked** [comment]
Also I have a comment not related to the issue...

I think you should provide fully built binaries that do not depend on the .NET framework, it makes the project more portable and easier for users.

I normally use this command `dotnet publish -r win-x86 -c Release -p:PublishSingleFile=true` to produce the builds and change the os version to make builds for all 3.

**Comment by TheAirBlow** [comment]
> Also I have a comment not related to the issue...
> 
> I think you should provide fully built binaries that do not depend on the .NET framework, it makes the project more portable and easier for users.
> 
> I normally use this command `dotnet publish -r win-x86 -c Release -p:PublishSingleFile=true` to produce the builds and change the os version to make builds for all 3.

It really inflates the filesize and it's probably just better to have .NET installed for other stuff I might be doing

**Comment by user8547** [comment]
Would be great if you could release a new release that has this feature as the current releases are not usable in practice.

**Comment by TheAirBlow** [comment]
> Would be great if you could release a new release that has this feature as the current releases are not usable in practice.

Yeah, I will tomorrow
