### ISSUE TITLE
Fetch mode doesn't work

### ISSUE THREAD

**Issue by michelle1574** [Samsung-Loki/Syndical#4]
Command prompt output:
PS F:\syndical> ./Syndical.Application -m Fetch -M SM-A510F -r XEO
Device: SM-A510F/XEO
Connecting to FUS server...

Fetching firmware list ----------------------------------------   0% 00:00:00 \

Exception occured: Input string was not in a correct format.

**Comment by TheAirBlow** [comment]
Duplicate of #6
