### ISSUE TITLE
Download Mode doesn't work

### ISSUE THREAD

**Issue by michelle1574** [Samsung-Loki/Syndical#6]
There are many problems I think, command line output:
C:\fixphone>Syndical.Application.exe -m DownloadDecrypt -M SM-A510F -r XEO -v A510FXXS8CTI7/A510FOXA8CSF3/A510FXXS8CSF3/A510FXXS8CTI7 -o SamsungFirmware.zip
Device: SM-A510F/XEO
Firmware: A510FXXS8CTI7/A510FOXA8CSF3/A510FXXS8CSF3/A510FXXS8CTI7
Connecting to FUS server...
Verifying firmware version...
Exception occured: Input string was not in a correct format.

**Comment by TheAirBlow** [comment]
I cannot see the full exception message. Please send the full logs

**Comment by TheAirBlow** [comment]
Closed, not enough information for a long time.
