### ISSUE TITLE
Trying to download old versions downloads newer ones

### ISSUE THREAD

**Issue by vrebagliati** [Samsung-Loki/Syndical#8]
Even though fetching available versions shows every version, when trying to download a really old version it downloads the 2nd newest one instead.

Example:
Running ' Syndical -m Fetch -M SM-M236B -r ARO ' returns

| Version                                                 | Android       | Size       | Latest |
|---------------------------------------------------------|---------------|------------|--------|
| M236BXXU2CWC1/M236BOWO2CWC1/M236BXXU2CWC1/M236BXXU2CWC1 | T(Android 13) | 5809879952 | False  |
| M236BXXU1AVB3/M236BOWO1AVB4/M236BXXU1AVB2/M236BXXU1AVB3 | S(Android 12) | 5730130240 | False  |
| M236BXXU1AVC4/M236BOWO1AVB4/M236BXXU1AVC4/M236BXXU1AVC4 | S(Android 12) | 5730130240 | False  |
| M236BXXS1AVDC/M236BOWO1AVB4/M236BXXU1AVC4/M236BXXS1AVDC | S(Android 12) | 5730130240 | False  |
| M236BXXU1BVK5/M236BOWO1BVK5/M236BXXU1BVK6/M236BXXU1BVK5 | T(Android 13) | 5809879952 | False  |
| M236BXXS2BWB1/M236BOWO2BWB1/M236BXXS2BWB1/M236BXXS2BWB1 | T(Android 13) | 5809879952 | False  |
| M236BXXU1AVH1/M236BOWO1AVH1/M236BXXU1AVG4/M236BXXU1AVH1 | S(Android 12) | 5730130240 | False  |
| M236BXXU1AVD2/M236BOWO1AVB4/M236BXXU1AVC4/M236BXXU1AVD2 | S(Android 12) | 5730130240 | False  |
| M236BXXU1AVG1/M236BOWO1AVE1/M236BXXU1AVE2/M236BXXU1AVG1 | S(Android 12) | 5730130240 | False  |
| M236BXXU1AVC1/M236BOWO1AVB4/M236BXXU1AVC1/M236BXXU1AVC1 | S(Android 12) | 5730130240 | False  |
| M236BXXU1AVC1/M236BOWO1AVB4/M236BXXU1AVC1/M236BXXU1AVC1 | T(Android 13) | 5809879952 | False  |

But when I try to download 'M236BXXU1AVC1/M236BOWO1AVB4/M236BXXU1AVC1/M236BXXU1AVC1' (The oldest one) by running:
' Syndical -m DownloadDecrypt -v M236BXXU1AVC1/M236BOWO1AVB4/M236BXXU1AVC1/M236BXXU1AVC1 -M SM-M236B -r ARO -f '

it downloads 'M236BXXU1BVK5/M236BOWO1BVK5/M236BXXU1BVK6/M236BXXU1BVK5' (The 2nd newest) instead

This issue seems to be because Samsung only stores the last 2 versions on their servers, There should be a warning about this as because of this I accidentally updated my phone loosing the chance to flash a custom recovery

Please fix this promptly, Thanks for your help
Valentino Rebagliati

**Comment by TheAirBlow** [comment]
It's a known problem for a long time already. At the moment no workaround
was found.

пн, 10 апр. 2023 г., 23:40 Valentino Rebagliati ***@***.***>:

**Comment by TheAirBlow** [comment]
Following up, the fact that are are two repeating file sizes should already
bell a ring.

вт, 11 апр. 2023 г., 00:30 TheAirBlow ***@***.***>:

**Comment by TheAirBlow** [comment]
Additionally, you skipped the warning in readme:
https://github.com/Samsung-Loki/Syndical#warning
